SELECT "Resources" AS TABLE_NAME, COUNT(*) AS N, CONV(BIT_XOR(CAST(CRC32(name) AS UNSIGNED)), 10, 16) AS CRC FROM resources GROUP BY 1
UNION
SELECT "Usages" AS TABLE_NAME, COUNT(*) AS N, CONV(BIT_XOR(CAST(CRC32(user_hash) AS UNSIGNED)), 10, 16) AS CRC FROM usages GROUP BY 1
UNION
SELECT "Users" AS TABLE_NAME, COUNT(*) AS N, CONV(BIT_XOR(CAST(CRC32(hash) AS UNSIGNED)), 10, 16) AS CRC FROM users GROUP BY 1;
