#!/usr/bin/env  python

# Copyright (C) 2012, Gustavo Duarte
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import print_function

import argparse
from stats_consolidation.db import *
from stats_consolidation.rrd_files import *
from stats_consolidation.consolidation import *

parser = argparse.ArgumentParser()
parser.add_argument('--db_user',required=True)
parser.add_argument('--db_pass',required=True)
parser.add_argument('--db_name',required=True)
parser.add_argument('--rrd_path',required=True)
parser.add_argument('--log_path',required=True)

args = parser.parse_args()

"""
try:
	db = DB_Stats (args.db_name, args.db_user, args.db_pass)
	db.create()
except Exception as e:
	print ("Creating DB: {}".format (str(e)


try:
	con = Consolidation(args.rrd_path, db)
	con.process_rrds()
except Exception as e:
	print ("Processing rrd file: {}".format(str(e)
"""
db = DB_Stats (args.db_name, args.db_user, args.db_pass)
db.create()


con = Consolidation(args.rrd_path, db)
con.process_rrds()
