#!/usr/bin/env  python

# Copyright (C) 2012, Gustavo Duarte
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from __future__ import print_function

import argparse
from stats_consolidation.db import *
import sys
parser = argparse.ArgumentParser()
parser.add_argument('--query',required=True)
parser.add_argument('--start_date',required=True)
parser.add_argument('--end_date',required=True)
parser.add_argument('--db_name',required=True)
parser.add_argument('--db_user',required=True)
parser.add_argument('--db_pass',required=True)

args = parser.parse_args()


"""try:"""
re = DB_Stats (args.db_name, args.db_user, args.db_pass)
re.connect()
if args.query == 'activity_most_used':
	activity = re.most_activity_used();
	print ("**************************************************************************************************************")
	print ("THE MOST USED ACTIVITY: {}, TIME: {} hrs / {} mins / {} secs".format(activity[0], activity[1]/60/60, activity[1]/60, activity[1]))
	print ("***************************************************************************************************************")

if args.query == 'frequency_usage':
	fres = re.frequency_usage();
	print("Frequency usage: {}".format(fres))
"""
print ("Error: {}".format(sys.exc_info()[0]))
"""
